apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: nlj63rt5n-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nlj63rt5n-python 
  name: nlj63rt5n-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: nlj63rt5n-python
    weight: 100 
